---
version: "2.0"

services:
  oasis-rofl-node:
    image: ubuntu:22.04
    
    expose:
      - port: 26656
        as: 26656
        to:
          - global: true
      - port: 9200
        as: 9200
        to:
          - global: true
    
    env:
      - NETWORK=testnet
      - OASIS_NODE_VERSION=24.2
      - DEBIAN_FRONTEND=noninteractive
    
    command:
      - "bash"
      - "-c"
    args:
      - >-
        apt-get update &&
        apt-get install -y curl jq git ca-certificates sudo &&
        useradd -m -s /bin/bash oasis &&
        git clone https://github.com/inversiones536/oasis_rofl_node.git /app &&
        chown -R oasis:oasis /app &&
        cd /app &&
        chmod +x scripts/*.sh &&
        sudo -u oasis ./scripts/setup.sh &&
        echo "Setup complete, starting node..." &&
        echo "NOTE: This is a basic client node. ROFL apps require SGX hardware." &&
        echo "To use ROFL, either:" &&
        echo "  1. Deploy on SGX-capable hardware" &&
        echo "  2. Use Oasis testnet's existing ROFL scheduler services" &&
        exec sudo -u oasis ./scripts/start-node.sh

profiles:
  compute:
    rofl-node:
      resources:
        cpu:
          units: 8.0
        memory:
          size: 32Gi
        storage:
          - size: 200Gi

  placement:
    akash:
      pricing:
        rofl-node:
          denom: uakt
          amount: 10000

deployment:
  oasis-rofl-node:
    akash:
      profile: rofl-node
      count: 1
